awstest/awstest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('quotes/', include('quotes.urls')),
    path('admin/', admin.site.urls),
]

awstest/quotes/urls.py
from django.urls import path

from .views import index, add_quote

app_name = 'quotes'
urlpatterns = [
    path('', index, name='index'),
    path('add/', add_quote, name='add'),
]

awstest/quotes/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Quote(models.Model):
    quote = models.CharField(max_length=255)
    pub_date = models.DateTimeField('Date entered', 
        auto_now_add=True,
        editable='False')

awstest/quotes/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse

from quotes.models import Quote

# Create your views here.
def index(request):
    rdm_quote = Quote.objects.order_by('?').first()
    template = loader.get_template('quotes/index.html')
    context = {
        'random_quote' : rdm_quote
    }
    return HttpResponse(template.render(context, request))

def add_quote(request):
    text = Quote(quote=request.POST['quote'])
    print("Text will be: " + text.quote)
    if text != "":
        new_quote = text
        new_quote.save()
        template = loader.get_template('quotes/index.html')
        context = {
            'random_quote' : new_quote
        }
        return HttpResponse(template.render(context, request))
    else:
        return render(request, 'quotes/index.html', {
            'error_message': "Please enter a quote"
        })
    

awstest/quotes/templates/quotes/index.html
<h1>Quote of the day</h1>
{% if random_quote %}
    <p>{{ random_quote.quote }}</p>
{% else %}
    {% if error_message %}
        <p>{{ error_message </p>
    {% else %}
        <p>No quotes available</p>
    {% endif %}
{% endif %}

<h1> Submit new quote</h1>
<form action="{% url 'quotes:add' %}" method="post">
{% csrf_token %}
Quote:<br>
<input type="text" name="quote" value="quote">
<br>
<br>
<input type="submit" value="submit">
</form>

awstest/quotes/templates/quotes/static.html
<h1>Quote of the day</h1>
<p>Plans are usesless but planning is essential</p>